### ISSUE TITLE
Error on npm run wasm

### ISSUE THREAD

**Issue by atmakup** [boyanio/angular-wasm#19]
When I used the latest master branch, and run npm run wasm, I am getting the below error 

Compiling wasm source for 3d-cube
docker run --rm -v C:\Users\Phanindra\Downloads\angular-wasm-master\angular-wasm-master:/src emscripten/emsdk emcc -Os src/app/wasm/3d-cube/soil/libSOIL.bc src/app/wasm/3d-cube/3d-cube.c -o src/assets/wasm/3d-cube.js -s LEGACY_GL_EMULATION=1 -Isrc/app/wasm/3d-cube/soil -s EXTRA_EXPORTED_RUNTIME_METHODS="['ccall']" -s FORCE_FILESYSTEM=1 -s MODULARIZE=1 -s EXPORT_NAME="Cube3dModule"
'docker' is not recognized as an internal or external command,
operable program or batch file.
child_process.js:674
    throw err;

**Comment by boyanio** [comment]
Hello. You need [docker](https://www.docker.com) to build the WebAssembly examples.

**Comment by WissemAouichi** [comment]
Hello, I have docker installed and i still have this issue appearing. Any idea what could be the cause of it? 
Thank you

**Comment by WissemAouichi** [comment]
After rechecking it tells me this : docker: invalid reference format.

**Comment by boyanio** [comment]
I have no idea, to be honest. Could it be this https://stackoverflow.com/questions/45682010/docker-invalid-reference-format ?
