### ISSUE TITLE
Fibonnacci working only with Chrome - Edge and Firefox timed out

### ISSUE THREAD

**Issue by GergoTot** [boyanio/angular-wasm#2]
Hi,

I was trying to load https://boyan.io/angular-wasm/fibonacci, and only under Chrome has worked.
I tried with the newest Firefox: 68.0.2 (64-bit). I tried with Edge version (can't find the exact version).
I tried with Chrome:  76.0.3809.100 (Official Build) (64-bit). So only with chrome is Fibonacci working... Firefox is frozen, Edge can load the results once, then i should restart for new success.  I tried under Windows 10 Home, but i tried with Firefox under Ubuntu 16.04 LTS as well. Under Linux it wasn't working as well. I tried to compile your code from master, and the same symptoms I have experienced. I used angular CLI version 8, but with package.json from master. It's very pitty because there are very very few examples can be found about angular with webassambly...

**Comment by boyanio** [comment]
Hi,

Thanks for reporting this. To be honest, I have also experienced issues with the Fibonacci module. It crashes often under different browsers, but I haven't had time to investigate the reasons. Have you tried the other modules? Do you experience any issues with them?

**Comment by GergoTot** [comment]
You are right, other webassambly part are working well. Only Fibonacci is crashed under Firefox and Edge (Chrome not!). From my point of view this issue is lower priority now.
