### ISSUE TITLE
Usecase with complex data types

### ISSUE THREAD

**Issue by ChristianWeyer** [boyanio/angular-wasm#9]
Hi!

it would be great to have a sample that uses complex types to pass in and out data from Angular to WASM.
Thanks.

**Comment by boyanio** [comment]
@ChristianWeyer very good idea. Can you come up with a scenario to showcase?

I am thinking about the following: Expose functions from WASM that manipulate RGB colors (e.g., lighten, darken) and pass RGB objects between Angular (JavaScript) and WASM to manipulate colors. How does it sound?

**Comment by ChristianWeyer** [comment]
This is not a bad idea.
Could we have nested complex types, not just int, string etc.?

**Comment by boyanio** [comment]
Are you thinking about something like this?

```
{
  "name": "...",
  "age": 30,
  "address": {
    "streetName": "...",
    "streetNumber": 12
  }
}
```

**Comment by ChristianWeyer** [comment]
Yep, exactly. Maybe add a list of something, as well ;-)

**Comment by ChristianWeyer** [comment]
Any idea when you might find time to fiddle with it? 😉

**Comment by boyanio** [comment]
@ChristianWeyer I managed to create a very simple demo with this. Let me know what you think and if you have any better idea :-)

**Comment by ChristianWeyer** [comment]
This is very nice - thanks for that!

A few other use cases come to mind, but I guess this is really great now.

**Comment by boyanio** [comment]
Feel free to improve the demos (add new ones, edit current ones) with a PR - always welcome. Or just open an issue here and I will check it when I have time
